package com.dazito.oauthexample.model.type;

public enum ResponseCode {
    CURRENT_USER_IS_NOT_ADMIN,
    EMAIL_NOT_MATCH,
    EMPTY_FIELD,
    ORGANIZATIONS_NOT_MUCH,
    PASSWORDS_NOT_MATCHES,
    PATH_NOT_EXIST,
    TYPE_MISMATCH,
    USER_WITH_SUCH_EMAIL_EXIST,
    NO_SUCH_ELEMENT,
    DO_NOT_HAVE_ACCESS,
    NO_FILE_ON_CHANNEL,
    CONTENT_NOT_EXIST
}